In [11]:
query = """
SELECT 
    SUM(Revenue) / COUNT(DISTINCT InvoiceNo) as avg_order_value
FROM sales
"""

pd.read_sql(query, conn)

   avg_order_value
0       480.865956

In [10]:
query = """
SELECT 
    Country,
    SUM(Revenue) as revenue
FROM sales
GROUP BY Country
ORDER BY revenue DESC
LIMIT 10
"""

pd.read_sql(query, conn)

          Country      revenue
0  United Kingdom  7308391.554
1     Netherlands   285446.340
2            EIRE   265545.900
3         Germany   228867.140
4          France   209024.050
5       Australia   138521.310
6           Spain    61577.110
7     Switzerland    56443.950
8         Belgium    41196.340
9          Sweden    38378.330

In [9]:
query = """
SELECT 
    CustomerID,
    SUM(Revenue) as total_spent
FROM sales
GROUP BY CustomerID
ORDER BY total_spent DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  CustomerID  total_spent
0    14646.0    280206.02
1    18102.0    259657.30
2    17450.0    194550.79
3    16446.0    168472.50
4    14911.0    143825.06
5    12415.0    124914.53
6    14156.0    117379.63
7    17511.0     91062.38
8    16029.0     81024.84
9    12346.0     77183.60

In [8]:
query = """
SELECT 
    Description,
    SUM(Revenue) as revenue
FROM sales
GROUP BY Description
ORDER BY revenue DESC
LIMIT 10
"""

pd.read_sql(query, conn)

                          Description    revenue
0         PAPER CRAFT , LITTLE BIRDIE  168469.60
1            REGENCY CAKESTAND 3 TIER  142592.95
2  WHITE HANGING HEART T-LIGHT HOLDER  100448.15
3             JUMBO BAG RED RETROSPOT   85220.78
4      MEDIUM CERAMIC TOP STORAGE JAR   81416.73
5                             POSTAGE   77803.96
6                       PARTY BUNTING   68844.33
7       ASSORTED COLOUR BIRD ORNAMENT   56580.34
8                              Manual   53779.93
9                  RABBIT NIGHT LIGHT   51346.20

In [7]:
query = """
SELECT 
    strftime('%Y-%m', InvoiceDate) as month,
    SUM(Revenue) as revenue
FROM sales
GROUP BY month
ORDER BY month
"""

pd.read_sql(query, conn)

      month      revenue
0   2010-12   572713.890
1   2011-01   569445.040
2   2011-02   447137.350
3   2011-03   595500.760
4   2011-04   469200.361
5   2011-05   678594.560
6   2011-06   661213.690
7   2011-07   600091.011
8   2011-08   645343.900
9   2011-09   952838.382
10  2011-10  1039318.790
11  2011-11  1161817.380
12  2011-12   518192.790

In [6]:
query = """
SELECT SUM(Revenue) as total_revenue
FROM sales
"""

pd.read_sql(query, conn)

   total_revenue
0    8911407.904

In [5]:
cursor.execute("SELECT * FROM sales LIMIT 5")
cursor.fetchall()

[('536365',
  '85123A',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  6,
  '2010-12-01 08:26:00',
  2.55,
  '17850.0',
  'United Kingdom',
  15.299999999999999),
 ('536365',
  '71053',
  'WHITE METAL LANTERN',
  6,
  '2010-12-01 08:26:00',
  3.39,
  '17850.0',
  'United Kingdom',
  20.34),
 ('536365',
  '84406B',
  'CREAM CUPID HEARTS COAT HANGER',
  8,
  '2010-12-01 08:26:00',
  2.75,
  '17850.0',
  'United Kingdom',
  22.0),
 ('536365',
  '84029G',
  'KNITTED UNION FLAG HOT WATER BOTTLE',
  6,
  '2010-12-01 08:26:00',
  3.39,
  '17850.0',
  'United Kingdom',
  20.34),
 ('536365',
  '84029E',
  'RED WOOLLY HOTTIE WHITE HEART.',
  6,
  '2010-12-01 08:26:00',
  3.39,
  '17850.0',
  'United Kingdom',
  20.34)]

In [4]:
df.to_sql("sales", conn, if_exists="replace", index=False)

397884

In [3]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/online_retail.csv", encoding="ISO-8859-1")

df = df.dropna(subset=["CustomerID", "Description"])
df = df[df["Quantity"] > 0]
df = df[df["UnitPrice"] > 0]

df["CustomerID"] = df["CustomerID"].astype(str)
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["Revenue"] = df["Quantity"] * df["UnitPrice"]

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [1]:
import sqlite3

conn = sqlite3.connect("../data/sales.db")
cursor = conn.cursor()